ck/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.index, name="index"),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path("blog/", views.blog, name="blog"),
    path("blog2/", views.blog2, name="blog2"),
    # path("blog/post/<uuid:id>/", views.post, name="post"),
    path("blog/post/<str:post_id_or_slug>/", views.post, name="post"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.core.validators import MaxLengthValidator
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.text import slugify
import uuid
from uuid import UUID

class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)
    slug = models.SlugField(unique=True, blank=True, max_length=255)

    class Meta:
        abstract = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.id or not isinstance(self.id, uuid.UUID):
            self.id = uuid.uuid4()
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()

    def save(self, *args, **kwargs):
        if not self.id:
            self.id = uuid.uuid4()
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        if not self.slug:
            self.slug = self.generate_slug()
        super().save(*args, **kwargs)
        
    def generate_slug(self):
        """
        Generate a unique slug for the model instance.
        Override this method in subclasses to provide custom behaviour.
        """
        base_slug = slugify(str(self))
        unique_slug = base_slug
        num = 1
        while self.__class__.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{base_slug}-{num}"
            num += 1
        return unique_slug

    def to_dict(self):
        """Returns a dictionary containing all key/values of the instance."""
        new_dict = {
            field.name: field.value_from_object(self)
            for field in self._meta.fields
        }
        
        datetime_format = '%Y-%m-%dT%H:%M:%S.%f'
        
        for field in self._meta.fields:
            if isinstance(field, (models.DateTimeField, models.DateField)) and field.name in new_dict:
                if new_dict[field.name]:
                    new_dict[field.name] = new_dict[field.name].strftime(datetime_format)
            elif isinstance(new_dict[field.name], UUID):
                new_dict[field.name] = str(new_dict[field.name])
        
        new_dict["__class__"] = self.__class__.__name__
        return new_dict
    
    def get_absolute_url(self):
        """
        Returns the URL to access a particular instance of the model.
        Override this method in subclasses to provide custom behavior.
        """
        return reverse(f'{self._meta.model_name}_detail', kwargs={'slug': self.slug})


class Category(BaseModel):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
    def generate_slug(self):
        return slugify(self.name)
    

class Tag(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    def generate_slug(self):
        return slugify(self.name)


class Post(BaseModel):
    title = models.CharField(max_length=255)
    # title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    body = CKEditor5Field('Content', config_name='extends')
    post_date = models.DateField(auto_now_add=True)
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    preview = models.TextField(blank=True,
                               help_text="Optional preview text for the post.",
                               validators=[MaxLengthValidator(limit_value=500)])
    post_image = models.ImageField(upload_to='post_images/', null=True, blank=True)

    @property
    def category_name(self):
        return self.category.name if self.category else None
    
    @property
    def title_tag(self):
        return f"{self.title} | {self.author} | {self.category}" 

    def __str__(self):
        return self.title

    def generate_slug(self):
        return slugify(self.title)

core/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Post, Category, Tag
from typing import Dict

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import DatabaseError
from django.http import HttpResponseNotFound, HttpResponseBadRequest
from django.db.models import Count
import uuid


# Create your views here.
def index(request):
    return render(request, 'core/base.html')

def blog(request):
    try:
        # Retrieve all posts
        posts_list = Post.objects.all()
        
        if not posts_list:
            return HttpResponse("No posts found.", status=404)

        # Create a Paginator object
        paginator = Paginator(posts_list, 10)  # Show 10 posts per page
        
        # Get the desired page number from the request
        page_number = request.GET.get('page', 1)
        
        try:
            # Get the page object for the current page number
            page_obj = paginator.get_page(page_number)
        except EmptyPage:
            return HttpResponseNotFound("The page number is out of range.")
        except PageNotAnInteger:
            return HttpResponseBadRequest("The page number is not an integer.")
        
        # Render the posts to a template
        return render(request, 'core/blog.html', {'page_obj': page_obj})

    except DatabaseError as e:
        # Log the error if needed
        print(f"Database error occurred: {e}")
        return HttpResponse("A database error occurred. Please try again later.", status=500)

    except Exception as e:
        # Log the error if needed
        print(f"An unexpected error occurred: {e}")
        return HttpResponse("An unexpected error occurred. Please try again later.", status=500)




def post(request, post_id_or_slug) -> Dict[str, str]:
    try:
        # First, try to get the post by UUID
        post_id = uuid.UUID(post_id_or_slug)
        post = get_object_or_404(Post, id=post_id)
    except ValueError:
        # If it's not a valid UUID, try to get the post by slug
        post = get_object_or_404(Post, slug=post_id_or_slug)
    category = post.category_name
    post = post.to_dict()
    post["category_name"] = category
    return render(request, 'core/post.html', {'post': post})

def blog2(request):
    query = request.GET.get('q', '')
    category_slug = request.GET.get('category')
    tag_slug = request.GET.get('tag')
    
    blog_posts = Post.objects.all().order_by('-created_at')
    
    if query:
        blog_posts = blog_posts.filter(title__icontains=query)
    if category_slug:
        blog_posts = blog_posts.filter(category__slug=category_slug)
    if tag_slug:
        blog_posts = blog_posts.filter(tags__slug=tag_slug)
        
    categories = Category.objects.annotate(post_count=Count('posts'))
    tags = Tag.objects.annotate(post_count=Count('posts'))
    
    paginator = Paginator(blog_posts, 4)  # Show 4 blog posts per page
    
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    # Calculate the range of pages to display
    max_pages = 5
    current_page = posts.number
    page_range = list(range(max(1, current_page - 2), min(paginator.num_pages + 1, current_page + 3)))
    
    # Add first and last page if they're not already in the range
    if 1 not in page_range:
        page_range.insert(0, 1)
        if 2 not in page_range:
            page_range.insert(1, '...')
    if paginator.num_pages not in page_range:
        if paginator.num_pages - 1 not in page_range:
            page_range.append('...')
        page_range.append(paginator.num_pages)
        
    context = {
        'posts': posts,
        'total_post_count': blog_posts.count(),
        'page_range': page_range,
        'category_count': {category.name: category for category in categories},
        'categories': categories,
        'tags': tags,
        'tag_count': {tag: tag.post_count for tag in tags},
        'current_category': category_slug,
        'current_tag': tag_slug,
        'query': query,
    }
    return render(request, 'core/blog2.html', context)

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title %}{{ company_name }}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  {% comment %}<!-- Additional Meta Tags -->{% endcomment %}
  <meta name="author" content="Your Name or Company" />

  {% comment %}<!-- Open Graph Tags (Facebook, Telegram, WhatsApp) -->{% endcomment %}
  <meta property="og:title" content="{% block og_title %}Default Title{% endblock %}" />
  <meta property="og:description" content="A brief description of your content" />
  <meta property="og:image" content="URL to an image representing your content" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:type" content="website" /> {% comment %}<!-- Can be article, video, etc. -->{% endcomment %}
  <meta property="og:site_name" content="Your Site Name" />
  <meta property="og:locale" content="en_US" />

  {% comment %}<!-- Twitter Card Tags (Twitter) -->{% endcomment %}
  <meta name="twitter:card" content="summary_large_image" /> {% comment %}<!-- Use "summary" if no large image is desired -->{% endcomment %}
  <meta name="twitter:title" content="Title of your content" />
  <meta name="twitter:description" content="A brief description of your content" />
  <meta name="twitter:image" content="URL to an image representing your content" />
  <meta name="twitter:url" content="URL of the page" />
  <meta name="twitter:site" content="@yourusername" /> {% comment %}<!-- Optional -->{% endcomment %}
  <meta name="twitter:creator" content="@creatorusername" /> {% comment %}<!-- Optional -->{% endcomment %}

  {% comment %}<!-- Favicons -->{% endcomment %}
  <link href="{% static 'core/img/favicon.png' %}" rel="icon">
  <link href="{% static 'core/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  {% comment %}<!-- Fonts -->{% endcomment %}
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  {% comment %}<!-- Vendor CSS Files -->{% endcomment %}
  <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  {% comment %}<!-- Main CSS File -->{% endcomment %}
  <link href="{% static 'core/css/main.css' %}" rel="stylesheet">

  {% comment %}<!-- Additional Header Links -->{% endcomment %}
  {% block customjs %}{% endblock %}

  {% comment %}<!-- =======================================================
  * Template Name: FlexStart
  * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Updated: Jun 29 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->{% endcomment %}
</head>

<body class="starter-page-page">

  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="{% url 'core:index' %}" class="logo d-flex align-items-center me-auto">
        {% comment %}<!-- Uncomment the line below if you also wish to use an image logo -->{% endcomment %}
        <img src="{% static 'core/img/logo.png' %}" alt="">
        <h1 class="sitename">{{ company_brand }}</h1>
      </a>


      <a class="btn-getstarted flex-md-shrink-0" href="index.html#about">Get Started</a>

    </div>
  </header>

  <main class="main">
    {% block content %}

    {% comment %}<!-- Page Title -->{% endcomment %}
    <div class="page-title">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Starter Page</h1>
              <p class="mb-0">Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Starter Page</li>
          </ol>
        </div>
      </nav>
    </div>{% comment %}<!-- End Page Title -->{% endcomment %}

    {% comment %}<!-- Starter Section Section -->{% endcomment %}
    <section id="starter-section" class="starter-section section">

      {% comment %}<!-- Section Title -->{% endcomment %}
      <div class="container section-title" data-aos="fade-up">
        <h2>Starter Section</h2>
        <p>Extended Section Title</p>
      </div>{% comment %}<!-- End Section Title -->{% endcomment %}

      <div class="container" data-aos="fade-up">
        <p>Use this page as a starter for your own custom pages.</p>
      </div>

    </section>{% comment %}<!-- /Starter Section Section -->{% endcomment %}

    {% endblock %}
  </main>

  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-lg-6">
            <h4>Join Our Newsletter</h4>
            <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
            <form action="forms/newsletter.php" method="post" class="php-email-form">
              <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your subscription request has been sent. Thank you!</div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="d-flex align-items-center">
            <span class="sitename">{{ company_name }}</span>
          </a>
          <div class="footer-contact pt-3">
            <p>{{ address_line_1 }}</p>
            <p>{{ address_line_2 }}</p>
            <p class="mt-3"><strong>Phone:</strong> <span>{{ phone_contact }}</span></p>
            <p><strong>Email:</strong> <span>{{ email }}</span></p>
          </div>
        </div>

        

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Pet Care</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Immunization</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Animal Care Shop</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Vet Appointments</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-12">
          <h4>Follow Us</h4>
          <p>Get the Latest in Animal Health and Wellness!</p>
          <div class="social-links d-flex">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href="{{ facebook }}"><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>

          </div>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright  {{ year }}</span> <strong class="px-1 sitename">{{ company_name }}</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        {% comment %}<!-- All the links in the footer should remain intact. -->{% endcomment %}
        {% comment %}<!-- You can delete the links only if you've purchased the pro version. -->{% endcomment %}
        {% comment %}<!-- Licensing information: https://bootstrapmade.com/license/ -->{% endcomment %}
        {% comment %}<!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->{% endcomment %}
        Built by <a href="https://impressohub.com/">Impressohub</a>
      </div>
    </div>

  </footer>

  {% comment %}<!-- Whatsapp Button -->{% endcomment %}
  <a href="https://wa.me/{{ whatsapp }}" id="whatsapp" class="whatsapp d-flex align-items-center justify-content-center" target="_blank"><i class="bi bi-whatsapp"></i></a>

  {% comment %}<!-- Scroll Top -->{% endcomment %}
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% comment %}<!-- Vendor JS Files -->{% endcomment %}
  <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'core/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'core/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'core/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'core/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'core/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'core/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'core/vendor/swiper/swiper-bundle.min.js' %}"></script>

  {% comment %}<!-- Main JS File -->{% endcomment %}
  <script src="{% static 'core/js/main.js' %}"></script>

</body>

</html>

core/templates/core/blog.html
{% extends "core/base.html" %} {% load static %} {% block title %}Post -
{{company_brand }}{% endblock %} {% block content %}

<h1>Post List</h1>

    <ul>
        {% for post in page_obj %}
            <li><a href="{% url 'core:post' id=post.id %}">{{ post.title }}</a> {{ post.id }}</li>
        {% empty %}
            <li>No posts available.</li>
        {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

core/templates/core/blog2.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Blog - {{company_brand }}{% endblock %}
{% block customjs %}<script src="{% static 'core/js/blog-pagination.js' %}" defer></script>{% endblock %}
{% block content %}

<!-- Page Title -->
<div class="page-title">
  <div class="heading">
    <div class="container">
      <div class="row d-flex justify-content-center text-center">
        <div class="col-lg-8">
          <h1>Blog</h1>
          <p class="mb-0">Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
        </div>
      </div>
    </div>
  </div>
  <nav class="breadcrumbs">
    <div class="container">
      <ol>
        <li><a href="{% url 'core:index' %}">Home</a></li>
        <li class="current">Blog</li>
      </ol>
    </div>
  </nav>
</div><!-- End Page Title -->

<div class="container">
  <div class="row">

    <div class="col-lg-8">

      <!-- Blog Posts Section -->
      <section id="blog-posts" class="blog-posts section">
        <div class="container">
          <div class="row gy-4">
            {% if posts %}
              {% for post in posts %}
                <div class="col-12">
                  <article class="rounded">
                    <div class="post-img d-flex justify-content-center align-items-center">
                      {% if post.post_image %}
                        <img src="{{ post.post_image.url }}" alt="{{ post.title }}" class="img-fluid">
                      {% else %}
                        <img src="{% static 'core/img/blog/blog-1.jpg' %}" alt="{{ post.title }}" class="img-fluid rounded-top">
                      {% endif %}
                    </div>
                    <h2 class="title">
                      <a href="{% url 'core:post' post.id %}">{{ post.title }}</a>
                    </h2>
                    <div class="meta-top">
                      <ul>
                        <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'core:post' post.id %}">{{ post.author }}</a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="{% url 'core:post' post.id %}"><time datetime="{{ post.date|date:'Y-m-d' }}">{{ post.post_date|date:"M d, Y" }}</time></a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="{% url 'core:post' post.id %}">{{ post.comments.count }} Comments</a></li>
                      </ul>
                    </div>
                    <div class="content">
                      <p>{{ post.preview|default:post.body|truncatewords:40|safe }}</p>
                      <div class="read-more">
                        <a href="{% url 'core:post' post.id %}">Read More</a>
                      </div>
                    </div>
                    <div class="tags">
                      {% for tag in post.tags.all %}
                        <a href="?tag={{ tag.slug }}">{{ tag.name }}</a>
                      {% endfor %}
                    </div>
                  </article>
                </div>
              {% endfor %}
            {% else %}
              <div class="col-12">
                <p>No posts to display.</p>
              </div>
            {% endif %}  
          </div>
        </div>
      </section>
      
      <!-- Blog Pagination Section -->
      <section id="blog-pagination" class="blog-pagination section">
        <div class="container">
          <div class="d-flex justify-content-center">
            <ul>
              {% if posts.has_previous %}
                <li><a href="?{% if request.GET.category %}category={{ request.GET.category }}&{% endif %}{% if request.GET.tag %}tag={{ request.GET.tag }}&{% endif %}page={{ posts.previous_page_number }}"><i class="bi bi-chevron-left"></i></a></li>
              {% endif %}
              
              {% for page_num in page_range %}
                {% if page_num == '...' %}
                  <li>...</li>
                {% else %}
                  <li><a href="?{% if query %}q={{ query }}&{% endif %}{% if current_category %}category={{ current_category }}&{% endif %}{% if current_tag %}tag={{ current_tag }}&{% endif %}page={{ page_num }}">
                    {{ page_num }}
                  </a></li>
                {% endif %}
              {% endfor %}
              
              {% if posts.has_next %}
                <li><a href="?{% if request.GET.category %}category={{ request.GET.category }}&{% endif %}{% if request.GET.tag %}tag={{ request.GET.tag }}&{% endif %}page={{ posts.next_page_number }}"><i class="bi bi-chevron-right"></i></a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </section>

    </div>

    <div class="col-lg-4 sidebar">

      <div class="widgets-container">

        <!-- Search Widget -->
        <div class="search-widget widget-item">

          <h3 class="widget-title">Search</h3>
          <form method="get" action="">
            <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Search posts...">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
          </form>

        </div><!--/Search Widget -->

        <!-- Categories Widget -->
        <div class="categories-widget widget-item">

          <h3 class="widget-title">Categories</h3>
          <ul class="mt-3">
            <li>
              <a href="{% url 'core:blog2' %}">
                All <span>({{ total_post_count }})</span>
              </a>
            </li>


            {% for category in categories %}
              <li>
                <a href="?category={{ category.slug }}" {% if category.slug == current_category %}class="active"{% endif %}>
                  {{ category.name }} <span>({{ category.post_count }})</span>
                </a>
              </li>
            {% endfor %}
          </ul>

        </div><!--/Categories Widget -->

        <!-- Recent Posts Widget -->
        <div class="recent-posts-widget widget-item">

          <h3 class="widget-title">Recent Posts</h3>

          <div class="post-item">
            <img src="{% static 'core/img/blog/blog-recent-1.jpg' %}" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Nihil blanditiis at in nihil autem</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div><!-- End recent post item-->

          <div class="post-item">
            <img src="{% static 'core/img/blog/blog-recent-2.jpg' %}" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Quidem autem et impedit</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div><!-- End recent post item-->

          <div class="post-item">
            <img src="{% static 'core/img/blog/blog-recent-3.jpg' %}" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Id quia et et ut maxime similique occaecati ut</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div><!-- End recent post item-->

          <div class="post-item">
            <img src="{% static 'core/img/blog/blog-recent-4.jpg' %}" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Laborum corporis quo dara net para</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div><!-- End recent post item-->

          <div class="post-item">
            <img src="{% static 'core/img/blog/blog-recent-5.jpg' %}" alt="" class="flex-shrink-0">
            <div>
              <h4><a href="blog-details.html">Et dolores corrupti quae illo quod dolor</a></h4>
              <time datetime="2020-01-01">Jan 1, 2020</time>
            </div>
          </div><!-- End recent post item-->

        </div><!--/Recent Posts Widget -->

        <!-- Tags Widget -->
        <div class="tags-widget widget-item">

          <h3 class="widget-title">Tags</h3>
          <ul>
            {% for tag in tags %}
              <li>
                <a href="?tag={{ tag.slug }}" {% if tag.slug == current_tag %}class="active"{% endif %}>
                  {{ tag.name }} ({{ tag.post_count }})
                </a>
              </li>
            {% endfor %}
          </ul>

        </div><!--/Tags Widget -->

      </div>

    </div>

  </div>
</div>
{% endblock %}

core/templates/core/post.html
{% extends "core/base.html" %} {% load static %} {% block title %}Post -
{{company_brand }}{% endblock %} {% block content %}

<h1>{{ post.title }}</h1>
<p>{{ post.body| safe }}</p>
<p>Published on: {{ post.post_date }}</p>

<ul>
    <li>{{ post.category_name }}</li>
</ul>

{% endblock %}